package com.eduvision.jdbc;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import org.springframework.stereotype.Repository;

import jakarta.annotation.PostConstruct;

/**
 * Concrete JDBC DAO for the {@code jdbc_attendance} table (inheritance + polymorphism).
 *
 * <p>On startup it creates its own portable table - the DDL below is valid on both H2 and
 * PostgreSQL - and it only has to implement the table-specific hooks of
 * {@link AbstractJdbcDao}; every CRUD method is inherited.
 */
@Repository
public class AttendanceJdbcDao extends AbstractJdbcDao<AttendanceRecord> {

    /** Portable identity DDL: H2 and PostgreSQL both accept this exact statement. */
    private static final String CREATE_TABLE =
            "CREATE TABLE IF NOT EXISTS jdbc_attendance ("
                    + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                    + "student_name VARCHAR(120) NOT NULL, "
                    + "present BOOLEAN NOT NULL)";

    public AttendanceJdbcDao(ConnectionFactory connections) {
        super(connections);
        createTable();
    }

    /** Ensures the table exists once the Spring bean is initialised (idempotent). */
    @PostConstruct
    public void init() {
        createTable();
    }

    /** Executes the portable {@code CREATE TABLE IF NOT EXISTS} DDL. */
    public void createTable() {
        try (Connection connection = open();
             Statement statement = connection.createStatement()) {
            statement.execute(CREATE_TABLE);
        } catch (SQLException e) {
            throw new JdbcDaoException("Could not create table " + tableName(), e);
        }
    }

    /** @return the table name (public accessor so the demo endpoint can report it). */
    public String table() {
        return tableName();
    }

    /** @return the JDBC URL this DAO connects to (public accessor for the demo endpoint). */
    public String connectionUrl() {
        return connections.url();
    }

    // ─────────────────────────────────────────────────────── table-specific hooks

    @Override
    protected String tableName() {
        return "jdbc_attendance";
    }

    @Override
    protected AttendanceRecord mapRow(ResultSet rs) throws SQLException {
        return new AttendanceRecord(
                rs.getLong("id"),
                rs.getString("student_name"),
                rs.getBoolean("present"));
    }

    @Override
    protected String[] insertColumns() {
        return new String[]{"student_name", "present"};
    }

    @Override
    protected void bindInsert(PreparedStatement ps, AttendanceRecord entity) throws SQLException {
        ps.setString(1, entity.getStudentName());
        ps.setBoolean(2, entity.isPresent());
    }

    @Override
    protected AttendanceRecord withId(AttendanceRecord entity, long id) {
        return entity.withId(id);
    }
}
